## Docker compose for keycloak
## Using internal H2 db
version: '3.7'
services:
  keycloak:
    image: coredge/keycloak:v21.1.1-0
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_DATABASE_VENDOR=dev-mem
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
