annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.5.0
description: A Library Helm Chart for grouping common logic between coredge charts.
  This chart is not deployable by itself.
keywords:
- common
- helper
- template
- function
- coredge
name: common
type: library
version: 2.5.0
